### PR TITLE
add 2 row for mutual friendships

### PR DESCRIPTION
**Pull request by JAAR91**
Created methods to have 2-row mutual friendships
- Every user will create an entry when a friend request is sent
- When a friend request is accepted the first row will be updated and a new one will be created for the user who accepted
- when deleting a friend both rows are removed
- when refusing a friend request just the first row that was created is deleted

### CODE REVIEW

**Review by jcy2704 — CHANGES_REQUESTED** [review]
# CHANGES REQUIRED 👀🤔

## Hey @JAAR91! You've done really great work here. Better than I expected. 🙌 However, there is still missing a feature in your project.

The posts that are posted by other users can only be seen by friends. If User A is not friends with User B then User A cannot see User B posts and vice versa.

- [x] Filter Users posts for only friends.

<hr>

### Keep the awesome work! 💪 Happy Coding for y'all!! 💻

**If you have any questions you can ask me on my Slack.**

**Best,**

**[💁‍♂️ Steven Jack Chung Yau](https://stevenchung.me)**

[LinkedIn](https://linkedin.com/in/stevenjchung) | [Twitter](https://twitter.com/_yiak) | [GitHub](https://github.com/jcy2704)

**Review by taiwo2 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED
@JAAR91 Great work for implementing 
 

- [x] Filter Users posts for only friends.
### however i can't see this 
- [x] UsersController#index displays all users with `Friend Request` button next to users who are not their friends already ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone3/userctr.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/final-project))
Kindly implement it. once done request for another review

**Comment by JAAR91** [comment]
Here is the add button code: 

https://github.com/JAAR91/ror-social-scaffold/blob/develop/app/helpers/friendships_helper.rb

**Review by carlos-ssh — CHANGES_REQUESTED** [review]
Hello [JAAR91](https://www.github.com/JAAr91) ✌🏽 ✌🏽 ✌🏽
I'm really impressed with your job.  👏🏽 👏🏽 👏🏽
Following the changes requested by our partners.
This is being giving more professional to your project.
I had the chance to review your project, it’s very clean. 
<hr>
<strong>Please make this next changes:</strong> <br>
- Fix the issue in your tests on RSpec.

After you finish and your tests are working well, request a code review again.

_Happy Coding!_ 👾👨🏽‍💻
[Carlos-SSH](https://www.github.com/carlos-ssh)

**Review by BrianSammit — APPROVED** [review]
STATUS: APPROVED :green_circle: :100: 
------------
Hello @JAAR91,  great job working on the required changes :clap: 
-------------
Now you can merge this branch :muscle: :100: 
HAPPY CODING!!! :smile: 

Well-Done-Applause

**Pull request merged**
